name: chat_app
description: A new project
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.0.3
  at_onboarding_flutter: ^3.0.1
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_chat_flutter: ^3.0.3
  at_contacts_flutter: ^4.0.0
  at_app_flutter: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

